// internal/analysis/active/taint/types.go
package taint

import (
	"net/url"
	"time"

	// Adherence to the canonical schemas is mandatory.
	"github.com/xkilldash9x/scalpel-cli/api/schemas"
)

// -- Constants --
const (
	JSCallbackSinkEvent      = "__scalpel_sink_event"
	JSCallbackExecutionProof = "__scalpel_execution_proof"
	JSCallbackShimError      = "__scalpel_shim_error"
)

// -- Core IAST Concepts --

// Event is the core interface for the CSP model. All data flowing to the correlation engine is an Event.
type Event interface {
	isEvent()
}

type SanitizationLevel int

const (
	SanitizationNone    SanitizationLevel = iota // Payload intact.
	SanitizationPartial                          // Canary found, structure modified.
)

// -- Data Structures (Definitions, State, Events, Findings) --

// ProbeDefinition: Blueprint for an attack vector.
type ProbeDefinition struct {
	Type        schemas.ProbeType `json:"type" yaml:"type"`
	Payload     string            `json:"payload" yaml:"payload"`
	Context     string            `json:"context" yaml:"context"`
	Description string            `json:"description" yaml:"description"`
}

// ActiveProbe: A specific, tracked instance of an injected probe.
type ActiveProbe struct {
	Type      schemas.ProbeType
	Key       string
	Value     string
	Canary    string
	Source    schemas.TaintSource
	CreatedAt time.Time
}

// SinkEvent: Reported by the JS shim.
type SinkEvent struct {
	Type       schemas.TaintSink `json:"type"`
	Value      string            `json:"value"`
	Detail     string            `json:"detail"`
	StackTrace string            `json:"stack"`
}
func (SinkEvent) isEvent() {}

// ExecutionProofEvent: Confirmation of payload execution.
type ExecutionProofEvent struct {
	Canary     string `json:"canary"`
	StackTrace string `json:"stack"`
}
func (ExecutionProofEvent) isEvent() {}

// ShimErrorEvent: Reports internal instrumentation failures.
type ShimErrorEvent struct {
	Error      string `json:"error"`
	Location   string `json:"location"`
	StackTrace string `json:"stack"`
}
func (ShimErrorEvent) isEvent() {}


// OASTInteraction: Local type for OAST events, implementing the Event interface.
type OASTInteraction struct {
	Canary          string
	Protocol        string
	SourceIP        string
	InteractionTime time.Time
	RawRequest      string
}
func (OASTInteraction) isEvent() {}

// CorrelatedFinding: The actionable intelligence generated by the correlation engine.
type CorrelatedFinding struct {
	TaskID            string
	TargetURL         string
	Sink              schemas.TaintSink
	Origin            schemas.TaintSource
	Value             string
	Canary            string
	Probe             ActiveProbe
	Detail            string
	IsConfirmed       bool
	SanitizationLevel SanitizationLevel
	StackTrace        string
	OASTDetails       *OASTInteraction
}

// -- Interfaces (Decoupling Points) --
type OASTProvider schemas.OASTProvider
type SessionContext schemas.SessionContext

type ResultsReporter interface {
	// Report must be thread-safe as it is called concurrently by the worker pool.
	Report(finding CorrelatedFinding)
}

// -- Configuration --

// SinkDefinition: Blueprint for JS instrumentation hooks.
type SinkDefinition struct {
	Name        string            `json:"Name" yaml:"name"`
	Type        schemas.TaintSink `json:"Type" yaml:"type"`
	Setter      bool              `json:"Setter" yaml:"setter"`
	ArgIndex    int               `json:"ArgIndex" yaml:"arg_index"`
	ConditionID string            `json:"ConditionID,omitempty" yaml:"condition_id,omitempty"`
}

// Config: Operational parameters for the Taint Analyzer.
type Config struct {
	TaskID string   `json:"task_id" yaml:"task_id"`
	Target *url.URL
	Probes []ProbeDefinition `json:"probes" yaml:"probes"`
	Sinks  []SinkDefinition  `json:"sinks" yaml:"sinks"`
	Interaction schemas.InteractionConfig `json:"interaction" yaml:"interaction"`
	AnalysisTimeout time.Duration         `json:"analysis_timeout" yaml:"analysis_timeout"`

	// Performance/Concurrency Tuning.
	// Controls the size of the correlation worker pool.
	CorrelationWorkers      int           `json:"correlation_workers" yaml:"correlation_workers"`
	EventChannelBuffer      int           `json:"event_channel_buffer" yaml:"event_channel_buffer"`
	FinalizationGracePeriod time.Duration `json:"finalization_grace_period" yaml:"finalization_grace_period"`
	ProbeExpirationDuration time.Duration `json:"probe_expiration_duration" yaml:"probe_expiration_duration"`
	CleanupInterval         time.Duration `json:"cleanup_interval" yaml:"cleanup_interval"`
	OASTPollingInterval     time.Duration `json:"oast_polling_interval" yaml:"oast_polling_interval"`
}